package hr.fer.zemris.dipl.lukasuman.fpga.bool.parsing.parser;

import hr.fer.zemris.dipl.lukasuman.fpga.bool.parsing.lexer.Lexer;
import hr.fer.zemris.dipl.lukasuman.fpga.bool.parsing.lexer.Token;
import hr.fer.zemris.dipl.lukasuman.fpga.util.Resetable;

/**
 * A lexicographical parser which uses {@link Token} generated by a {@link Lexer} to construct a new object.
 * See {@link BoolParser} as an example.
 * @param <T> Type of the token.
 * @param <S> Type of the returned object.
 */
public interface Parser<T extends Token, S> extends Resetable {

    S parse(Lexer<T> lexer);
}
