package hr.fer.zemris.dipl.lukasuman.fpga.bool.parsing.lexer;

/**
 * This enumeration describes the various token types generated by the {@link BoolLexer}.
 */
public enum BoolTokenType {

    /**
     * A string composed of consecutive word characters (alphabetical and numerical).
     */
    WORD,

    /**
     * Left parenthesis. All three types "(", "[", "{" are considered the same.
     */
    PARENTHESIS_LEFT,

    /**
     * Right parenthesis. All three types ")", "]", "}" are considered the same.
     */
    PARENTHESIS_RIGHT,

    /**
     * End of line token.
     */
    EOL,

    /**
     * End of file token.
     */
    EOF
}
